# Generated by Django 2.2.5 on 2019-10-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_bloggers', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
