# Generated by Django 2.2.5 on 2019-11-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_bloggers', '0005_entry_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('-date_added',), 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-date_added',)},
        ),
    ]
