# Generated by Django 2.2.5 on 2019-11-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_bloggers', '0006_auto_20191102_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='read_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
