# Generated by Django 2.2.5 on 2019-11-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_bloggers', '0007_entry_read_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
