# Generated by Django 2.2.5 on 2019-11-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_bloggers', '0009_entry_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='picture',
            field=models.ImageField(blank=True, upload_to='picture/%Y%m%d/'),
        ),
    ]
