# Generated by Django 2.2.5 on 2019-11-08 05:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_bloggers', '0011_auto_20191107_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
