# Generated by Django 2.2.5 on 2019-11-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_bloggers', '0012_auto_20191108_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
